// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_skills_create_skill = {
    title: string;
    description?: (string | null);
    category_id: string;
    is_published?: boolean;
    file: (Blob | File);
};

export type Body_skills_replace_skill_file = {
    file: (Blob | File);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SkillCategoriesPublic = {
    data: Array<SkillCategoryPublic>;
    count: number;
};

export type SkillCategoryCreate = {
    name: string;
    description?: (string | null);
    sort_order?: number;
    is_active?: boolean;
};

export type SkillCategoryPublic = {
    name: string;
    description?: (string | null);
    sort_order?: number;
    is_active?: boolean;
    id: string;
    created_at?: (string | null);
};

export type SkillCategoryUpdate = {
    name?: (string | null);
    description?: (string | null);
    sort_order?: (number | null);
    is_active?: (boolean | null);
};

export type SkillDownloadPublic = {
    url: string;
    expires_in: number;
};

export type SkillPublic = {
    title: string;
    description?: (string | null);
    is_published?: boolean;
    id: string;
    category_id: string;
    category_name: string;
    file_name: string;
    file_size: number;
    file_content_type?: (string | null);
    created_by_id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type SkillPublishUpdate = {
    is_published: boolean;
};

export type SkillsPublic = {
    data: Array<SkillPublic>;
    count: number;
};

export type SkillUpdate = {
    title?: (string | null);
    description?: (string | null);
    category_id?: (string | null);
    is_published?: (boolean | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SkillCategoriesReadSkillCategoriesData = {
    includeInactive?: boolean;
    limit?: number;
    skip?: number;
};

export type SkillCategoriesReadSkillCategoriesResponse = (SkillCategoriesPublic);

export type SkillCategoriesCreateSkillCategoryData = {
    requestBody: SkillCategoryCreate;
};

export type SkillCategoriesCreateSkillCategoryResponse = (SkillCategoryPublic);

export type SkillCategoriesUpdateSkillCategoryData = {
    categoryId: string;
    requestBody: SkillCategoryUpdate;
};

export type SkillCategoriesUpdateSkillCategoryResponse = (SkillCategoryPublic);

export type SkillCategoriesDeleteSkillCategoryData = {
    categoryId: string;
};

export type SkillCategoriesDeleteSkillCategoryResponse = (Message);

export type SkillsReadSkillsData = {
    categoryId?: (string | null);
    limit?: number;
    onlyPublished?: boolean;
    skip?: number;
};

export type SkillsReadSkillsResponse = (SkillsPublic);

export type SkillsCreateSkillData = {
    formData: Body_skills_create_skill;
};

export type SkillsCreateSkillResponse = (SkillPublic);

export type SkillsReadSkillData = {
    skillId: string;
};

export type SkillsReadSkillResponse = (SkillPublic);

export type SkillsUpdateSkillData = {
    requestBody: SkillUpdate;
    skillId: string;
};

export type SkillsUpdateSkillResponse = (SkillPublic);

export type SkillsDeleteSkillData = {
    skillId: string;
};

export type SkillsDeleteSkillResponse = (Message);

export type SkillsReplaceSkillFileData = {
    formData: Body_skills_replace_skill_file;
    skillId: string;
};

export type SkillsReplaceSkillFileResponse = (SkillPublic);

export type SkillsPublishSkillData = {
    requestBody: SkillPublishUpdate;
    skillId: string;
};

export type SkillsPublishSkillResponse = (SkillPublic);

export type SkillsGetSkillDownloadData = {
    skillId: string;
};

export type SkillsGetSkillDownloadResponse = (SkillDownloadPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);