server {
  listen 80;
  resolver 127.0.0.11 valid=10s ipv6=off;
  set $backend_upstream backend:8000;
  set $frontend_upstream frontend:80;

  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;

  location /api/ {
    proxy_pass http://$backend_upstream;
  }

  location /docs {
    proxy_pass http://$backend_upstream;
  }

  location /redoc {
    proxy_pass http://$backend_upstream;
  }

  location /openapi.json {
    proxy_pass http://$backend_upstream;
  }

  location /minio/ {
    proxy_pass http://minio:9000/;
    proxy_set_header Host minio:9000;
  }

  location / {
    proxy_pass http://$frontend_upstream;
  }
}
